version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: xray-manager-db-dev
    environment:
      POSTGRES_DB: xray_manager
      POSTGRES_USER: xray_manager
      POSTGRES_PASSWORD: xray_manager_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_dev_data:/var/lib/postgresql/data

volumes:
  pg_dev_data:
