version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nexus-xray-db-dev
    environment:
      POSTGRES_DB: nexus_xray
      POSTGRES_USER: nexus_xray
      POSTGRES_PASSWORD: nexus_xray_pass
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-dev:/var/lib/postgresql/data
