// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/nodehub/v1/hub.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServerMessage 是 Server 下发给 Agent 的指令
type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // 指令唯一 ID
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"` // 指令方法名 (如 UpdateConfig, RestartXray)
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`     // 指令负载 (JSON 编码)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_nodehub_v1_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodehub_v1_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_nodehub_v1_hub_proto_rawDescGZIP(), []int{0}
}

func (x *ServerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServerMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// NodeMessage 是 Agent 上报给 Server 的消息
type NodeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // 对应 ServerMessage 的 ID
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"` // 事件类型 (如 StatsReport, XrayStatus)
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`      // 操作是否成功
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`   // 消息负载 (JSON 编码)
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	Seq           int64                  `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`    // 序列号，用于流式消息排序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_proto_nodehub_v1_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nodehub_v1_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_proto_nodehub_v1_hub_proto_rawDescGZIP(), []int{1}
}

func (x *NodeMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeMessage) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *NodeMessage) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NodeMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NodeMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NodeMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

var File_proto_nodehub_v1_hub_proto protoreflect.FileDescriptor

const file_proto_nodehub_v1_hub_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/nodehub/v1/hub.proto\x12\n" +
	"nodehub.v1\"K\n" +
	"\rServerMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"\x7f\n" +
	"\vNodeMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x03R\x03seq2U\n" +
	"\x10NodeAgentService\x12A\n" +
	"\aSession\x12\x17.nodehub.v1.NodeMessage\x1a\x19.nodehub.v1.ServerMessage(\x010\x01BGZEgithub.com/shangui999/nexus-xray/internal/common/proto/nodehub/v1b\x06proto3"

var (
	file_proto_nodehub_v1_hub_proto_rawDescOnce sync.Once
	file_proto_nodehub_v1_hub_proto_rawDescData []byte
)

func file_proto_nodehub_v1_hub_proto_rawDescGZIP() []byte {
	file_proto_nodehub_v1_hub_proto_rawDescOnce.Do(func() {
		file_proto_nodehub_v1_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nodehub_v1_hub_proto_rawDesc), len(file_proto_nodehub_v1_hub_proto_rawDesc)))
	})
	return file_proto_nodehub_v1_hub_proto_rawDescData
}

var file_proto_nodehub_v1_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_nodehub_v1_hub_proto_goTypes = []any{
	(*ServerMessage)(nil), // 0: nodehub.v1.ServerMessage
	(*NodeMessage)(nil),   // 1: nodehub.v1.NodeMessage
}
var file_proto_nodehub_v1_hub_proto_depIdxs = []int32{
	1, // 0: nodehub.v1.NodeAgentService.Session:input_type -> nodehub.v1.NodeMessage
	0, // 1: nodehub.v1.NodeAgentService.Session:output_type -> nodehub.v1.ServerMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_nodehub_v1_hub_proto_init() }
func file_proto_nodehub_v1_hub_proto_init() {
	if File_proto_nodehub_v1_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nodehub_v1_hub_proto_rawDesc), len(file_proto_nodehub_v1_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nodehub_v1_hub_proto_goTypes,
		DependencyIndexes: file_proto_nodehub_v1_hub_proto_depIdxs,
		MessageInfos:      file_proto_nodehub_v1_hub_proto_msgTypes,
	}.Build()
	File_proto_nodehub_v1_hub_proto = out.File
	file_proto_nodehub_v1_hub_proto_goTypes = nil
	file_proto_nodehub_v1_hub_proto_depIdxs = nil
}
